
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 13 12:08:08 CET 2018
//----------------------------------------------------

package toucan.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int TYPEVAR = 13;
  public static final int TABFERMER = 3;
  public static final int PARENTHESEOUVR = 5;
  public static final int VARIABLE = 14;
  public static final int POINTVIRGULE = 2;
  public static final int BRACKETOUVR = 7;
  public static final int CONSTANTE = 17;
  public static final int OPERAPIDE = 19;
  public static final int EGALE = 4;
  public static final int EOF = 0;
  public static final int OPERATION = 18;
  public static final int error = 1;
  public static final int BOUCLEFOR = 11;
  public static final int COMPARATEUR = 16;
  public static final int BOUCLEWHILE = 12;
  public static final int PARENTHESEFERM = 6;
  public static final int TABOUVRIR = 15;
  public static final int CONDITIONNELLEELSE = 10;
  public static final int CONDITIONNELLEIF = 9;
  public static final int BRACKETFERM = 8;
}

